### ISSUE TITLE
OTrP - protocol does not allow "taname" to be set

### ISSUE THREAD

**Issue by andyatyeo** [hannestschofenig/tschofenig-ids#22]
Each TA has a "taname" attribute (along with the "taid"). "taname" is meant to be a friendly readable string describing the TA, and is returned from GetDeviceInfo in the dsi information.
However, the protocol does not allow us to set the "taname" when we install an TA - so a TEE will never be able to return it in the dsi.
Either we get rid of "taname" altogether, or we expand the protocol as follows:
- Expand InstallTATBSRequest to contain "taname" (in the content section, following "taid"). This will allow a TSM to set "taname". Update message description/schema, and sample messages
- Expand getTAInformationTBS to output "taname" in the json. This will allow applications on the device to learn the "taname"

If there is agreement to the update, I can make the changes to the document.

**Comment by nickcookigp** [comment]
Removed taname from non-ietf work
