### ISSUE TITLE
Not clear what public key format is used for "spaik"/"teespaik", plus inconsistencies in messages where the key type ("spaiktype"/"teespaiktype") is returned

### ISSUE THREAD

**Issue by andyatyeo** [hannestschofenig/tschofenig-ids#25]
What format (of publickey) is "teespaik"? (the public key returned from CreateSD), and how does the TSM know whether this is RSA or ECC?
Currently OTrP spec does not indidate the public key format (and there are many to formats to choose from), so TEE and TSM might choose different formats (e.g. TEE outputs pkcs1 publickey, but TSM expects JWK publickey)
Note that currently, "spaiktype" is not returned by CreateSD but is returned by UpdateSD, and also in the "dsi". (so we either need to return "spaiktype" from CreateSDResponse, or remove it altogether if it turns out to be not needed)
Some publickey formats (such as JWT) encapsulate the type of key (in the "kty" attribute), (therefore making "spaiktype" unnecessary), while other publickey formats require you to know the key type before you parse it.
Therefore we need to define the public key type in the specification for the "spaik"/"teespaik"  - (is "spaik"=="teespaik"? is this the same element with different names in different messages and if so can the same name be used throughout?)
* Suggested resolution:
 ** update GetDeviceTEEStateTBSResponse/"dsi" to indicate that "spaik" is JWK format
 ** update CreateSDResponse and UpdateSDResponse to indicate that "teespaik" is JWK format 
 * Since JWT format encapsulates the key type ("kty"), this means "spaiktype" (and "teespaiktype") is not needed anymore, and can be removed, so
 ** remove "teespaiktype" from UpdateSDResponse
 ** remove "spaiktype" from "dsi"
 * These changes would make GetDeviceStateResponse ,CreateSDResponse, and UpdateSDResponse sample messages out of date (these would ultimately need to show JWK format publickeys for "spaik" and "teespaik" and not show the removed "spaiktype" or "teespaiktype" attributes)..

**Comment by andyatyeo** [comment]
would also mean that B64 encoding of the publickey (in "dsi", and CreateSDResponse/UpdateSDResponse) is not needed, as the JWK object can be represented without B64 encoding.

**Comment by nickcookigp** [comment]
SP-AIK and TEE-SPAIK are the same thing. In the non-IETF work I have already included this JWK format and gone with spaik as the common used element name
