### ISSUE TITLE
Ambiguity of asymmetric encryption mechanism/padding when using spaik. No provision for ECC spaik encryption.

### ISSUE THREAD

**Issue by andyatyeo** [hannestschofenig/tschofenig-ids#29]
Ambiguity of asymmetric encryption mechanism/padding when using spaik. No provision for ECC spaik encryption.

**Comment by andyatyeo** [comment]
updated previous comment to indicate ECDH-ES (not ECDH-ES+A256KW) for the ECC case, since this is what JWA spec pushes harder. Note that our profile for JWE currently specifies ECDH-ES+A128W - it is worth looking at changing this to ECDH-ES (again - since JWA spec marks this as "Recommended+" (whereas ECDH-ES+A128W is just "Recommended").

**Comment by nickcookigp** [comment]
ECDH-ES has been adopted in the non-IETF spec work draft

**Comment by andyatyeo** [comment]
Updated original entry to reflect discussions, to be consistent with recommendations from issue 28, and to show a json sample of what encrypted_ta would look like. Note that the question of whether to use OAEP padding for the RSA encryption (throughout OTrP) is still outstanding

**Comment by nickcookigp** [comment]
Adopted the new encrypted_ta format suggestion above in non-IETF work
