### ISSUE TITLE
Carl's review of draft-fossati-tls-attestation-02

### ISSUE THREAD

**Issue by thomas-fossati** [hannestschofenig/tschofenig-ids#63]
* In the Section 3 overview, is the CBOR message wrapper always elected?
* The nonce definitions should be 8..2^16-1 in section 5 (instead of 0..2^16-1).
* It may be worth stating that clients and servers are expected to be able to verify more than one evidence type but only generate one type and perhaps signal this by using “type(s)” when referring to proposals and “types” when referring to requests.
* Is a hint list needed in addition to evidence_proposal (similar to or perhaps reusing certificate_authorities)?
* In the second bullet of 6.2, is the incompatibility that results in an error limited to evidence_request? The next to last paragraph of the section permits incompatibility with evidence_proposal.
* In 7.2, is the expectation that attestation is only done at onboarding time (so that the device just authenticates with the key without presenting evidence going forward)?
* As attestation results spec is considered, it may be that the product of executing a certificate request protocol is the means. This would better fit with how the attested keys I have worked with work but would not provide the platform indications that may be sought in this context. If key and platform attestation were decoupled in this way, then the CertificateEntry structure would get more complicated (to bundle a certificate containing key attestation result indication with some fresh platform attestation).

**Comment by hannestschofenig** [comment]
Transferred over to https://github.com/yaronf/draft-tls-attestation/issues/29
